/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chat {
  'id' : string,
  'participants' : Array<Principal>,
  'messages' : List,
  'lastActivity' : Time,
  'createdAt' : Time,
}
export interface FileReference { 'hash' : string, 'path' : string }
export type List = [] | [[Message, List]];
export interface Message {
  'id' : string,
  'content' : string,
  'sender' : Principal,
  'encrypted' : boolean,
  'timestamp' : Time,
}
export type Time = bigint;
export interface User {
  'bio' : [] | [string],
  'principal' : Principal,
  'username' : string,
  'createdAt' : Time,
  'profilePicture' : [] | [string],
}
export interface _SERVICE {
  'addGroupMember' : ActorMethod<[string, Principal], undefined>,
  'createChat' : ActorMethod<[Principal], string>,
  'createGroup' : ActorMethod<[string], string>,
  'deleteChatForEveryone' : ActorMethod<[string], undefined>,
  'deleteChatForMe' : ActorMethod<[string], undefined>,
  'deleteMessageForEveryone' : ActorMethod<[string, string], undefined>,
  'deleteMessageForMe' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'findExistingChat' : ActorMethod<[Principal, Principal], [] | [string]>,
  'getChatList' : ActorMethod<[], Array<Chat>>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getGroupMembers' : ActorMethod<[string], Array<Principal>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getUserByPrincipal' : ActorMethod<[Principal], [] | [User]>,
  'getUserByUsername' : ActorMethod<[string], [] | [User]>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'updateBio' : ActorMethod<[string], undefined>,
  'updateProfilePicture' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];