/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Message {
    id: string;
    content: string;
    sender: Principal;
    encrypted: boolean;
    timestamp: Time;
}
export interface Chat {
    id: string;
    participants: Array<Principal>;
    messages: List;
    lastActivity: Time;
    createdAt: Time;
}
export type Time = bigint;
export interface FileReference {
    hash: string;
    path: string;
}
export interface User {
    bio?: string;
    principal: Principal;
    username: string;
    createdAt: Time;
    profilePicture?: string;
}
export type List = [Message, List] | null;
export interface backendInterface {
    addGroupMember(groupId: string, member: Principal): Promise<void>;
    createChat(participant: Principal): Promise<string>;
    createGroup(name: string): Promise<string>;
    deleteChatForEveryone(chatId: string): Promise<void>;
    deleteChatForMe(chatId: string): Promise<void>;
    deleteMessageForEveryone(chatId: string, messageId: string): Promise<void>;
    deleteMessageForMe(messageId: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    findExistingChat(participant1: Principal, participant2: Principal): Promise<string | null>;
    getChatList(): Promise<Array<Chat>>;
    getFileReference(path: string): Promise<FileReference>;
    getGroupMembers(groupId: string): Promise<Array<Principal>>;
    getMessages(chatId: string): Promise<Array<Message>>;
    getUserByPrincipal(principal: Principal): Promise<User | null>;
    getUserByUsername(username: string): Promise<User | null>;
    listFileReferences(): Promise<Array<FileReference>>;
    registerFileReference(path: string, hash: string): Promise<void>;
    registerUser(username: string): Promise<void>;
    sendMessage(chatId: string, content: string): Promise<void>;
    updateBio(bio: string): Promise<void>;
    updateProfilePicture(path: string): Promise<void>;
}
import type { Chat as _Chat, List as _List, Message as _Message, Time as _Time, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGroupMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMember(arg0, arg1);
            return result;
        }
    }
    async createChat(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createChat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChat(arg0);
            return result;
        }
    }
    async createGroup(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0);
            return result;
        }
    }
    async deleteChatForEveryone(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatForEveryone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatForEveryone(arg0);
            return result;
        }
    }
    async deleteChatForMe(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatForMe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatForMe(arg0);
            return result;
        }
    }
    async deleteMessageForEveryone(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessageForEveryone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessageForEveryone(arg0, arg1);
            return result;
        }
    }
    async deleteMessageForMe(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessageForMe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessageForMe(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async findExistingChat(arg0: Principal, arg1: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findExistingChat(arg0, arg1);
                return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findExistingChat(arg0, arg1);
            return from_candid_opt_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async getChatList(): Promise<Array<Chat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatList();
                return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatList();
            return from_candid_vec_n2(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getGroupMembers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMembers(arg0);
            return result;
        }
    }
    async getMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getUserByPrincipal(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPrincipal(arg0);
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPrincipal(arg0);
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserByUsername(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByUsername(arg0);
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByUsername(arg0);
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateBio(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBio(arg0);
            return result;
        }
    }
    async updateProfilePicture(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(arg0);
            return result;
        }
    }
}
function from_candid_Chat_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chat): Chat {
    return from_candid_record_n4(uploadFile, downloadFile, value);
}
function from_candid_List_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _List): List {
    return from_candid_opt_n6(uploadFile, downloadFile, value);
}
function from_candid_User_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n10(uploadFile, downloadFile, value);
}
function from_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_Message, _List]]): [Message, List] | null {
    return value.length === 0 ? null : from_candid_tuple_n7(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n9(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    principal: Principal;
    username: string;
    createdAt: _Time;
    profilePicture: [] | [string];
}): {
    bio?: string;
    principal: Principal;
    username: string;
    createdAt: Time;
    profilePicture?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n1(uploadFile, downloadFile, value.bio)),
        principal: value.principal,
        username: value.username,
        createdAt: value.createdAt,
        profilePicture: record_opt_to_undefined(from_candid_opt_n1(uploadFile, downloadFile, value.profilePicture))
    };
}
function from_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    participants: Array<Principal>;
    messages: _List;
    lastActivity: _Time;
    createdAt: _Time;
}): {
    id: string;
    participants: Array<Principal>;
    messages: List;
    lastActivity: Time;
    createdAt: Time;
} {
    return {
        id: value.id,
        participants: value.participants,
        messages: from_candid_List_n5(uploadFile, downloadFile, value.messages),
        lastActivity: value.lastActivity,
        createdAt: value.createdAt
    };
}
function from_candid_tuple_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Message, _List]): [Message, List] {
    return [
        value[0],
        from_candid_List_n5(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_vec_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chat>): Array<Chat> {
    return value.map((x)=>from_candid_Chat_n3(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}